# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vS9-UCncsiqbRrQ3fzC956DLSXG5Hsh7
"""

import os, time, math, random
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from copy import deepcopy

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
from torchdiffeq import odeint

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ── Config ────────────────────────────────────────────────────────────────────
class Config:
    gif_path     = "/content/drive/MyDrive/NeuralAppearanceProject/data/RGB_dynamic_textures/molding_bread.gif"   # ← your GIF here

    # Resolution
    size         = 128    # training resolution (paper uses 128)
    sample_size  = 256    # inference resolution

    # Data
    n_frames     = 100    # frames to sample from GIF

    # Latent space  (paper: 3 RGB + 9 aug = 12)
    n_rgb        = 3
    n_aug        = 9
    n_channels   = n_rgb + n_aug

    # Architecture
    base_dim     = 32     # channel width at level 0  (paper: 32 but wider = better quality)
    dim_mults    = (1, 2) # 2-level UNet: 64, 128 channels  (paper: 3-level 1,2,4)

    # ODE time range
    t_i  = -1.0   # warm-up starts
    t_s  =  0.0   # generation starts
    t_e  =  5.0   # generation ends

    # Online training (paper's Algorithm 1)
    n_iters      = 20_000
    refresh_rate = 6       # R in the paper — segments per cycle
    lr           = 5e-4

    # ODE solver
    rtol         = 1e-2
    atol         = 1e-2

    # Loss weights
    w_gram       = 1.0
    w_swd        = 0.5

    # VGG layers for both losses
    vgg_layers   = [3, 8, 15]   # relu1_2, relu2_2, relu3_3

    # Ablations
    use_warmup   = True
    use_ode      = True   # False → 0th-order baseline

    # Inference
    n_synth_frames = 50
    n_trans_frames = 100

cfg = Config()

def load_gif(path, size, n_frames):
    gif = Image.open(path)
    all_frames = []
    for i in range(gif.n_frames):
        gif.seek(i)
        frame = gif.convert("RGB")
        w, h = frame.size
        s = min(w, h)
        frame = frame.crop(((w-s)//2, (h-s)//2, (w+s)//2, (h+s)//2))
        frame = frame.resize((size, size), Image.LANCZOS)
        all_frames.append(np.array(frame, dtype=np.float32) / 255.0)

    indices = np.linspace(0, len(all_frames)-1, n_frames, dtype=int)
    frames  = np.stack([all_frames[i] for i in indices])
    frames  = frames.transpose(0, 3, 1, 2) * 2.0 - 1.0
    return torch.from_numpy(frames).to(device)   # [N, 3, H, W] in [-1,1]

print("Loading GIF...")
exemplars   = load_gif(cfg.gif_path, cfg.size, cfg.n_frames)
frame_times = torch.linspace(cfg.t_s, cfg.t_e, cfg.n_frames, device=device)
print(f"Exemplars: {exemplars.shape}")

class VGGFeatures(nn.Module):
    def __init__(self, layers):
        super().__init__()
        vgg = models.vgg16(weights=models.VGG16_Weights.DEFAULT).features
        self.slices = nn.ModuleList()
        prev = 0
        for l in layers:
            self.slices.append(nn.Sequential(*list(vgg.children())[prev:l+1]))
            prev = l + 1
        for p in self.parameters():
            p.requires_grad_(False)
        mean = torch.tensor([0.485, 0.456, 0.406]).view(1,3,1,1)
        std  = torch.tensor([0.229, 0.224, 0.225]).view(1,3,1,1)
        self.register_buffer("mean", mean)
        self.register_buffer("std",  std)

    def forward(self, x):
        # x: [B, 3, H, W] in [-1,1]
        x = (x * 0.5 + 0.5 - self.mean) / self.std
        feats = []
        for s in self.slices:
            x = s(x)
            feats.append(x)
        return feats


def gram_matrix(feat):
    B, C, H, W = feat.shape
    f = feat.view(B, C, H*W)
    return torch.bmm(f, f.transpose(1,2)) / (C * H * W)


def gram_loss(feats_pred, feats_target):
    loss = 0.0
    for fp, ft in zip(feats_pred, feats_target):
        loss = loss + F.mse_loss(gram_matrix(fp), gram_matrix(ft))
    return loss


def swd_loss(feats_pred, feats_target, n_proj=64):
    """
    Sliced Wasserstein Distance on VGG features — same as paper's D_Global.
    Projects features onto random directions and measures 1D Wasserstein distance.
    """
    loss = 0.0
    for fp, ft in zip(feats_pred, feats_target):
        B, C, H, W = fp.shape
        fp_flat = fp.view(B, C, -1).mean(0).T   # [H*W, C]
        ft_flat = ft.view(B, C, -1).mean(0).T

        # Random projections
        proj = F.normalize(torch.randn(C, n_proj, device=fp.device), dim=0)
        fp_proj = fp_flat @ proj   # [H*W, n_proj]
        ft_proj = ft_flat @ proj

        fp_sorted = fp_proj.sort(dim=0).values
        ft_sorted = ft_proj.sort(dim=0).values
        loss = loss + F.mse_loss(fp_sorted, ft_sorted)
    return loss


vgg_feat = VGGFeatures(cfg.vgg_layers).to(device)
print("Loss functions ready")

class CircularConv2d(nn.Conv2d):
    """3×3 conv with circular padding — enables tileable textures."""
    def __init__(self, in_c, out_c):
        super().__init__(in_c, out_c, 3, padding=0)

    def forward(self, x):
        x = F.pad(x, (1,1,1,1), mode="circular")
        return super().forward(x)


class SinusoidalEmbedding(nn.Module):
    def __init__(self, dim):
        super().__init__()
        half = dim // 2
        freqs = torch.exp(-math.log(10000) * torch.arange(half) / max(half-1, 1))
        self.register_buffer("freqs", freqs)

    def forward(self, t):
        if t.dim() == 0:
            t = t.unsqueeze(0)
        emb = t[:,None] * self.freqs[None,:]
        return torch.cat([emb.sin(), emb.cos()], dim=-1)  # [B, dim]


class ResBlock(nn.Module):
    """
    Conv → GroupNorm → AdaGN (time conditioning) → SiLU → Conv → GroupNorm.
    Same structure as paper's ConvBlock.
    """
    def __init__(self, in_c, out_c, time_dim):
        super().__init__()
        self.conv1   = CircularConv2d(in_c, out_c)
        self.norm1   = nn.GroupNorm(min(8, out_c), out_c)
        self.conv2   = CircularConv2d(out_c, out_c)
        self.norm2   = nn.GroupNorm(min(8, out_c), out_c)

        # AdaGN: time → scale + shift
        self.time_proj = nn.Linear(time_dim, out_c * 2)
        nn.init.zeros_(self.time_proj.weight)
        nn.init.zeros_(self.time_proj.bias)

        # Skip connection if channel count changes
        self.skip = nn.Conv2d(in_c, out_c, 1) if in_c != out_c else nn.Identity()

    def forward(self, x, te):
        # te: [B, time_dim]
        sc = self.time_proj(te).view(te.shape[0], -1, 1, 1)
        scale, shift = sc.chunk(2, dim=1)

        h = self.conv1(x)
        h = self.norm1(h)
        h = h * (scale + 1) + shift   # AdaGN
        h = F.silu(h)
        h = self.conv2(h)
        h = self.norm2(h)
        h = F.silu(h)
        return h + self.skip(x)


class UNetODEFunc(nn.Module):
    """
    2-level UNet ODE function.
    Paper uses 3-level; 2-level is ~80K params and runs fine on T4 at 128px.

    Architecture:
      init_conv (1×1)
      → down0: ResBlock(C, C)   → downsample 2×
      → down1: ResBlock(C, 2C)
      → mid:   ResBlock(2C, 2C)
      → up0:   upsample 2× → ResBlock(2C+C, C)  [skip from down0]
      → out:   ResBlock(C+C_in, C) → 1×1 conv → sigmoid → recentre
    """
    def __init__(self, n_channels, base_dim, dim_mults, time_emb_dim=64):
        super().__init__()
        dims   = [base_dim * m for m in dim_mults]   # e.g. [64, 128]
        time_dim = base_dim * 4

        # Time embedding: sinusoidal → MLP
        self.sin_emb  = SinusoidalEmbedding(time_emb_dim)
        self.time_mlp = nn.Sequential(
            nn.Linear(time_emb_dim, time_dim),
            nn.SiLU(),
            nn.Linear(time_dim, time_dim),
        )

        # Initial 1×1 projection
        self.init_conv = nn.Conv2d(n_channels, dims[0], 1)

        # Down path
        self.down0     = ResBlock(dims[0], dims[0], time_dim)
        self.downsamp  = nn.Conv2d(dims[0], dims[0], 3, stride=2, padding=1)
        self.down1     = ResBlock(dims[0], dims[1], time_dim)

        # Bottleneck
        self.mid       = ResBlock(dims[1], dims[1], time_dim)

        # Up path
        self.up0       = ResBlock(dims[1] + dims[0], dims[0], time_dim)

        # Final output
        self.final_res = ResBlock(dims[0] + n_channels, dims[0], time_dim)
        self.final_out = nn.Conv2d(dims[0], n_channels, 1)
        nn.init.zeros_(self.final_out.weight)
        nn.init.zeros_(self.final_out.bias)

        total = sum(p.numel() for p in self.parameters())
        print(f"UNetODEFunc params: {total:,}")

    def forward(self, t, z):
        B = z.shape[0]
        t_b = t.expand(B) if t.dim() == 0 else t
        te  = self.time_mlp(self.sin_emb(t_b))   # [B, time_dim]

        # Encode
        x0 = F.silu(self.init_conv(z))            # [B, d0, H, W]
        h0 = self.down0(x0, te)                   # [B, d0, H, W]
        h1 = self.down1(self.downsamp(h0), te)    # [B, d1, H/2, W/2]

        # Bottleneck
        hm = self.mid(h1, te)                     # [B, d1, H/2, W/2]

        # Decode — upsample and concat skip
        hu = F.interpolate(hm, scale_factor=2, mode="bilinear", align_corners=False)
        hu = torch.cat([hu, h0], dim=1)           # skip from down0
        hu = self.up0(hu, te)                     # [B, d0, H, W]

        # Final with input skip (helps ODE learn residuals)
        out = torch.cat([hu, z], dim=1)
        out = self.final_res(out, te)
        out = torch.sigmoid(self.final_out(out))  # bounded [0,1]
        out = out - 0.5                           # recentre to [-0.5, 0.5]
        return out

class UNetZerothOrder(nn.Module):
    """
    Same UNet topology but maps (noise, t) → image directly.
    No ODE integration — tests whether the ODE formulation itself matters.
    """
    def __init__(self, n_channels, base_dim, dim_mults, time_emb_dim=64):
        super().__init__()
        dims     = [base_dim * m for m in dim_mults]
        time_dim = base_dim * 4

        self.sin_emb  = SinusoidalEmbedding(time_emb_dim)
        self.time_mlp = nn.Sequential(
            nn.Linear(time_emb_dim, time_dim),
            nn.SiLU(),
            nn.Linear(time_dim, time_dim),
        )
        self.init_conv = nn.Conv2d(n_channels, dims[0], 1)
        self.down0     = ResBlock(dims[0], dims[0], time_dim)
        self.downsamp  = nn.Conv2d(dims[0], dims[0], 3, stride=2, padding=1)
        self.down1     = ResBlock(dims[0], dims[1], time_dim)
        self.mid       = ResBlock(dims[1], dims[1], time_dim)
        self.up0       = ResBlock(dims[1] + dims[0], dims[0], time_dim)
        self.final_res = ResBlock(dims[0] + n_channels, dims[0], time_dim)
        self.final_out = nn.Conv2d(dims[0], n_channels, 1)
        self.tanh      = nn.Tanh()

    def forward(self, noise, t):
        B = noise.shape[0]
        t_b = t.expand(B) if t.dim() == 0 else t
        te  = self.time_mlp(self.sin_emb(t_b))

        x0 = F.silu(self.init_conv(noise))
        h0 = self.down0(x0, te)
        h1 = self.down1(self.downsamp(h0), te)
        hm = self.mid(h1, te)
        hu = F.interpolate(hm, scale_factor=2, mode="bilinear", align_corners=False)
        hu = torch.cat([hu, h0], dim=1)
        hu = self.up0(hu, te)
        out = torch.cat([hu, noise], dim=1)
        out = self.final_res(out, te)
        return self.tanh(self.final_out(out))

def make_time_segments(t_s, t_e, R):
    """
    Divide generation phase [t_s, t_e] into R-1 equal segments.
    Returns the R boundary points.
    """
    return torch.linspace(t_s, t_e, R, device=device)


def seed_noise(size, n_channels):
    return torch.randn(1, n_channels, size, size, device=device)


def latent_to_rgb(z):
    return z[:, :3]


def train(cfg, exemplars, frame_times, vgg_feat):
    if cfg.use_ode:
        model = UNetODEFunc(cfg.n_channels, cfg.base_dim,
                            cfg.dim_mults).to(device)
    else:
        model = UNetZerothOrder(cfg.n_channels, cfg.base_dim,
                                cfg.dim_mults).to(device)

    opt = torch.optim.Adam(model.parameters(), lr=cfg.lr)
    sched = torch.optim.lr_scheduler.ReduceLROnPlateau(
        opt, patience=1000, factor=0.5
    )

    # Segment boundaries for online training
    seg_bounds = make_time_segments(cfg.t_s, cfg.t_e, cfg.refresh_rate)

    history = {"loss": [], "gram": [], "swd": [], "iter": []}

    print(f"\nTraining {cfg.n_iters} iters"
          f"  |  mode={'ODE' if cfg.use_ode else '0th-order'}"
          f"  |  warmup={'on' if cfg.use_warmup else 'off'}")

    # Online state — persists across iterations within one cycle
    z0_online = seed_noise(cfg.size, cfg.n_channels)
    t0_online = torch.tensor(cfg.t_i, device=device)
    seg_idx   = 0   # which segment we're integrating toward

    t0_wall = time.time()

    for it in range(cfg.n_iters):
        opt.zero_grad()

        k = it % cfg.refresh_rate   # position within current cycle

        if cfg.use_ode:
            if k == 0:
                # Start of a new cycle: fresh noise, integrate warm-up phase
                z0_online = seed_noise(cfg.size, cfg.n_channels)
                t0_online = torch.tensor(cfg.t_i, device=device)
                t1        = torch.tensor(cfg.t_s, device=device)
                seg_idx   = 0
            else:
                # Continue from last state, integrate to next segment boundary
                seg_idx = min(k, len(seg_bounds) - 1)
                t1 = seg_bounds[seg_idx]

            # Integrate from (z0_online, t0_online) to t1
            t_span = torch.stack([t0_online, t1])
            traj   = odeint(model, z0_online, t_span,
                            rtol=cfg.rtol, atol=cfg.atol, method="adaptive_heun")
            z1 = traj[-1]

            # Compute loss against the closest exemplar frame
            t1_val    = t1.item()
            frame_idx = int(torch.argmin(torch.abs(frame_times -
                            torch.tensor(t1_val, device=device))).item())
            rgb_pred  = latent_to_rgb(z1)

            # Update online state
            z0_online = z1.detach()
            t0_online = t1.clone().detach()

        else:
            # 0th-order: random frame each time
            z0     = seed_noise(cfg.size, cfg.n_channels)
            frame_idx = random.randint(0, cfg.n_frames - 1)
            t_val  = frame_times[frame_idx]
            rgb_pred = latent_to_rgb(model(z0, t_val))

        rgb_tgt = exemplars[frame_idx].unsqueeze(0)

        # Resize if needed (sample_size != training size)
        if rgb_pred.shape[-1] != rgb_tgt.shape[-1]:
            rgb_pred = F.interpolate(rgb_pred, size=rgb_tgt.shape[-2:],
                                     mode="bilinear", align_corners=False)

        # ── Loss ──────────────────────────────────────────────────────────────
        fp = vgg_feat(rgb_pred)
        ft = vgg_feat(rgb_tgt)

        l_gram = gram_loss(fp, ft)
        l_swd  = swd_loss(fp, ft)
        loss   = cfg.w_gram * l_gram + cfg.w_swd * l_swd

        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        opt.step()
        sched.step(loss.item())

        # ── Log ───────────────────────────────────────────────────────────────
        if it % 200 == 0:
            elapsed = time.time() - t0_wall
            eta     = elapsed / (it + 1) * (cfg.n_iters - it - 1)
            print(f"  {it:6d}/{cfg.n_iters}"
                  f"  loss={loss.item():.4f}"
                  f"  gram={l_gram.item():.4f}"
                  f"  swd={l_swd.item():.4f}"
                  f"  {elapsed:.0f}s  ETA {eta:.0f}s")
            history["loss"].append(loss.item())
            history["gram"].append(l_gram.item())
            history["swd"].append(l_swd.item())
            history["iter"].append(it)

    print(f"\nDone in {time.time()-t0_wall:.0f}s")
    return model, history


model, history = train(cfg, exemplars, frame_times, vgg_feat)

@torch.no_grad()
def run_inference(model, cfg):
    size = cfg.sample_size
    z_noise = seed_noise(size, cfg.n_channels)

    def to_numpy(t):
        img = (t * 0.5 + 0.5).clamp(0, 1)
        return (img.squeeze(0).permute(1,2,0).cpu().numpy() * 255).astype(np.uint8)

    synth, trans = [], []

    if cfg.use_ode:
        # Warm-up: tI → tS
        t_wu = torch.linspace(cfg.t_i, cfg.t_s,
                              cfg.n_synth_frames + 1, device=device)
        traj_wu = odeint(model, z_noise, t_wu,
                         rtol=cfg.rtol, atol=cfg.atol, method="adaptive_heun")
        for i in range(len(traj_wu)):
            synth.append(to_numpy(latent_to_rgb(traj_wu[i])))

        # Generation: tS → tE
        z_ts = traj_wu[-1]
        t_ge = torch.linspace(cfg.t_s, cfg.t_e,
                              cfg.n_trans_frames + 1, device=device)
        traj_ge = odeint(model, z_ts, t_ge,
                         rtol=cfg.rtol, atol=cfg.atol, method="adaptive_heun")
        for i in range(len(traj_ge)):
            trans.append(to_numpy(latent_to_rgb(traj_ge[i])))
    else:
        for t_val in torch.linspace(cfg.t_i, cfg.t_s, cfg.n_synth_frames):
            synth.append(to_numpy(latent_to_rgb(model(z_noise, t_val))))
        for t_val in torch.linspace(cfg.t_s, cfg.t_e, cfg.n_trans_frames):
            trans.append(to_numpy(latent_to_rgb(model(z_noise, t_val))))

    return synth, trans


print("Running inference...")
synth_frames, trans_frames = run_inference(model, cfg)
print(f"Synthesis: {len(synth_frames)} frames  |  Transition: {len(trans_frames)} frames")

def show_strip(frames, title, n=8):
    idx = np.linspace(0, len(frames)-1, min(n, len(frames)), dtype=int)
    fig, axes = plt.subplots(1, len(idx), figsize=(2.2*len(idx), 2.5))
    if len(idx) == 1:
        axes = [axes]
    for ax, i in zip(axes, idx):
        ax.imshow(frames[i])
        ax.axis("off")
        ax.set_title(f"t={i}", fontsize=8)
    fig.suptitle(title, fontsize=10)
    plt.tight_layout()
    plt.show()


def show_comparison(trans, exemplars, n=6):
    idx = np.linspace(0, min(len(trans), exemplars.shape[0])-1, n, dtype=int)
    fig, axes = plt.subplots(2, len(idx), figsize=(2.5*len(idx), 5))
    for col, i in enumerate(idx):
        axes[0, col].imshow(trans[i])
        axes[0, col].axis("off")
        axes[0, col].set_title(f"model t={i}", fontsize=7)

        ex = (exemplars[i].cpu().float() * 0.5 + 0.5).clamp(0,1)
        ex = (ex.permute(1,2,0).numpy() * 255).astype(np.uint8)
        ex_pil = Image.fromarray(ex).resize(
            (trans[i].shape[1], trans[i].shape[0]), Image.LANCZOS)
        axes[1, col].imshow(np.array(ex_pil))
        axes[1, col].axis("off")
        axes[1, col].set_title(f"input t={i}", fontsize=7)

    axes[0, 0].set_ylabel("Model", fontsize=8)
    axes[1, 0].set_ylabel("Exemplar", fontsize=8)
    plt.suptitle("Model (top) vs Input GIF (bottom)", fontsize=10)
    plt.tight_layout()
    plt.show()


def plot_loss(history):
    fig, axes = plt.subplots(1, 2, figsize=(12, 3))
    axes[0].plot(history["iter"], history["loss"], label="total")
    axes[0].set_title("Total loss")
    axes[0].set_xlabel("Iteration")
    axes[0].grid(alpha=0.3)

    axes[1].plot(history["iter"], history["gram"], label="Gram", alpha=0.8)
    axes[1].plot(history["iter"], history["swd"],  label="SWD",  alpha=0.8)
    axes[1].set_title("Loss components")
    axes[1].set_xlabel("Iteration")
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.show()


plot_loss(history)
show_strip(synth_frames, "Synthesis — warm-up (noise → initial appearance)")
show_strip(trans_frames, "Transition — generation (follows dynamic texture)")
show_comparison(trans_frames, exemplars)